# This is a sample build configuration for Scala.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        caches:
          - sbt
          - ivy2
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install -y openjfx
          - curl -sL https://deb.nodesource.com/setup_8.x | bash -
          - apt-get install -y nodejs
          - sbt test